name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        emacs_version: ['25.1', '25.2', '25.3', '26.1', '27.1', '28.1', '28.2', '29.1', '29.2', '29.3', '29.4', '30.1', 'snapshot']
        cask_version: ['snapshot']

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Cask
      uses: cask/setup-cask@master
      with:
        version: 'snapshot'

    - name: Install dependencies
      run: cask install

    - name: Test
      run: make test

    - name: SSH into container on failure
      if: ${{ false }}
      # You can use this if statement to enable this during development.
      #if: ${{ failure() }}
      uses: lhotari/action-upterm@v1
      with:
        ## limits ssh access and adds the ssh public key for the user which triggered the workflow
        limit-access-to-actor: true
